jobs:
- job: Build
  displayName: Build Maven Project
  pool:
   name: default
   demands: agent.os -equals Linux
  steps:
  - task: cURLUploader@2
    displayName: 'Curl Upload'
    inputs:
      files: $(System.DefaultWorkingDirectory)/target/HelloWorld.war
      authType: UserAndPass
      url: SCP://121.36.13.207/
      remotePath: /root/HelloWorld.war
      options: '-k'
      username: 'root'
      password: $(AWS_AGENT_PASSWD)
- deployment: PushToAWS
  displayName: DeployTask
  environment: 
    name: testEnv
    resourceType: VirtualMachine
    tags: HW207
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment
  dependsOn: Build
  condition: succeeded()