jobs:
- job: Build
  displayName: Build Maven Project
  steps:
  - task: Maven@3
    displayName: 'Maven Package'
    inputs:
      mavenPomFile: 'pom.xml'
  - task: cURLUploader@2
    inputs：
    files: '$(System.DefaultWorkingDirectory)/*.war'
    authType: 'UserAndPass'
    username: 'root'
    password: 'fE3imQbTEBE='
    url: 'SCP://121.36.13.207:/root/'