# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

steps:
- task: SSH@0
  displayName: 'Run shell inline on remote machine'
  inputs:
    sshEndpoint: HW207
    runOptions: inline

    inline: cat /etc/*release