jobs:
- job: Build
  displayName: Build Maven Project
  pool:
    name: default
    demands: agent.os -equals Linux
  steps:
  - task: Maven@3
    displayName: 'Maven Package'
    inputs:
      mavenPomFile: 'pom.xml'
  - task: PublishBuildArtifacts@1
    displayName: 'Copy Files to artifact staging directory'
    inputs:
      artifactName: Helloworld

- job: Deploy
  pool:
    name: default
    demands: agent.os -equals Linux
  steps:
  - checkout: none
  - task: DownloadBuildArtifacts@0
    displayName: 'Download Build Artifacts'
    inputs:
      artifactName: Helloworld