jobs:
- job: Build
  displayName: Build Maven Project
  pool:
   name: default
   demands: agent.os -equals Linux
  steps:
  - task: Maven@3
    displayName: 'Maven Package'
    inputs:
      mavenPomFile: 'pom.xml'
  - task: cURLUploader@2
    displayName: 'Curl Upload'
    inputs:
      files: $(System.DefaultWorkingDirectory)/target/*.war
      authType: UserAndPass
      url: SCP://121.36.13.207/
      remotePath: /root/
      options: '-k'
      username: 'root'
      password: $(AWS_AGENT_PASSWD)
- deployment: PushToAWS
  displayName: DeployTask
  environment: 
    name: testEnv
    resourceType: VirtualMachine
    tags: HW207
  strategy:
    runOnce:
      deploy:
        steps:
        - script: echo my first deployment